name: '01a gets triggered by Push and Pull'

# Controls when the workflow will run
on: [push, pull_request] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #login to Azure
      # Runs a single command using the runners shell
      - name: TRIGGERED by a Push and a Pull!
        run: echo Oh noes
          

