name: '01c gets triggered when a pull request is closed'

# Controls when the workflow will run
on: 
  pull_request: 
    types: [closed] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #login to Azure
      # Runs a single command using the runners shell
      - name: TRIGGERED by aclosed pull request
        run: echo Oh noes
          
     
