name: '04 Deploy Bicep file'

on:
  # push:
  #   branches:
      # - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: Deploy Bicep Template
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          resource-group-name: bitbashdemo
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          template-file: ./storageAccount.bicep
          parameters: '{"storageAccountPrefix": "gh"}'

