name: '05 work in stages'

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #login to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.ClientID }}
          tenant-id: ${{ secrets.TenantID }}
          subscription-id: ${{ secrets.SubscriptionID }}

      - name: build Bicep file
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az bicep build --file logAnalyticsWorkspace.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.ref == 'refs/heads/main' }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #login to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.ClientID }}
          tenant-id: ${{ secrets.TenantID }}
          subscription-id: ${{ secrets.SubscriptionID }}
        
      - name: Deploy Log Analytics workspace
        uses: Azure/arm-deploy@v1
        id: law
        with:
          scope: resourcegroup
          resourceGroupName: GitHubDemo
          template: 'logAnalyticsWorkspace.bicep'
          deploymentName: "ghlaw${{github.run_id}} "
          parameters: "logAnalyticsWorkspaceName=ghlaw"
          
      - name: Deploy WebApp
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: GitHubDemo
          template: 'WebAppSolution.bicep'
          deploymentName: "ghapp${{github.run_id}} "
          parameters: "webappName=ghexample4bes serverFarmName=ghexample4bes workspaceResourceId=${{steps.law.outputs.logAnalyticsWorkspaceResourceID}}"

