name: '07 final flow'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: build Bicep file
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az bicep build --file logAnalyticsWorkspace.bicep

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps: 
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: Deploy LAW
        uses: azure/bicep-deploy@v2
        id: law
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          resource-group-name: bitbashdemo
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          template-file: ./logAnalyticsWorkspace.bicep
          parameters: '{"logAnalyticsWorkspaceName": "ghlaw"}'

      - name: Deploy WebApp
        uses: azure/bicep-deploy@v2
        id: webapp
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          resource-group-name: bitbashdemo
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          template-file: ./WebAppSolution.bicep
          parameters: '{"webappName":"ghexample4bes2", "serverFarmName":"ghexample4bes", "workspaceResourceId":"${{steps.law.outputs.logAnalyticsWorkspaceResourceID}}" }'
          